import { renderEmail } from './templates'

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * Draining email_outbox.
 *
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║ THE TABLE IS A QUEUE, NOT A LOG. Nothing here deletes a row. A sent row   ║
 * ║ keeps sent_at, a failing row keeps its error and its attempt count, and   ║
 * ║ an exhausted row keeps everything — the record of what happened is the    ║
 * ║ only way to answer "why did this person never get their result".         ║
 * ║                                                                          ║
 * ║ TWO CEILINGS, FOR DIFFERENT REASONS:                                     ║
 * ║   batch  — how much one run will attempt, so a cron tick stays bounded.  ║
 * ║   daily  — Resend's free tier is 100/day. Publishing results for 300     ║
 * ║            staff is ONE action that would be triple the daily quota, and  ║
 * ║            0007 built this queue precisely so that is delayed, not lost.  ║
 * ║                                                                          ║
 * ║ The daily count is measured from rows already sent today rather than      ║
 * ║ tracked in a counter, because a counter and the table can disagree and    ║
 * ║ the table is the truth.                                                   ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 * ═══════════════════════════════════════════════════════════════════════════
 */

/** Resend's free tier. Override per environment, never exceed silently. */
export const DEFAULT_DAILY_CAP = 100
export const DEFAULT_BATCH = 25

/** 0007: `attempts < 5` is in the queue index; give-up must match it exactly. */
export const MAX_ATTEMPTS = 5

/**
 * Addresses that provably cannot receive mail, ever.
 *
 * ┌───────────────────────────────────────────────────────────────────────────┐
 * │ RFC 2606 RESERVES example.com/net/org and the .test, .example and         │
 * │ .invalid TLDs precisely so they can never be routed; .local is mDNS and   │
 * │ never leaves the LAN. Every seed script, demo fixture and check run in    │
 * │ this repo enqueues to them — 54 of the 57 rows left after 0083 were       │
 * │ exactly that, and three of those were generated by a check run hours      │
 * │ earlier.                                                                  │
 * │                                                                           │
 * │ Attempting them is not merely wasted: each one is a live API call to the  │
 * │ provider that will be refused, and a burst of refusals from one account   │
 * │ is what abuse detection is built to notice. They are failed here, before  │
 * │ any call, and given no retries — retrying a reserved domain cannot ever   │
 * │ succeed.                                                                  │
 * └───────────────────────────────────────────────────────────────────────────┘
 */
const UNDELIVERABLE = /@(?:.+.)?(?:example.(?:com|net|org)|test|example|invalid|local)$|.(?:test|example|invalid|local)$/i

export function isUndeliverable(email: string): boolean {
  return UNDELIVERABLE.test(email.trim().toLowerCase())
}

export interface OutboxRow {
  id: string
  to_email: string
  to_user_id: string | null
  subject: string
  template: string
  payload: Record<string, unknown>
  priority: number
  scheduled_for: string
  attempts: number
}

export interface Recipient {
  locale: string
  name: string | null
}

export interface SendResult {
  ok: boolean
  error?: string
}

export interface DrainDeps {
  /** Unsent, due, not exhausted — priority then age. Bounded by `limit`. */
  claim(limit: number): Promise<OutboxRow[]>
  /** Rows already sent since midnight, for the daily ceiling. */
  sentToday(): Promise<number>
  /** preferred_locale + full_name, when the recipient still exists. */
  recipient(userId: string | null): Promise<Recipient>
  send(input: { to: string; subject: string; html: string; text: string }): Promise<SendResult>
  markSent(id: string): Promise<void>
  /** Records the error and bumps attempts; sets failed_at only at MAX_ATTEMPTS. */
  markFailed(id: string, attempts: number, error: string): Promise<void>
  appUrl(): string | null
}

export interface DrainOptions {
  batch?: number
  dailyCap?: number
  /** Renders and reports without sending. Nothing is marked. */
  dryRun?: boolean
}

export interface DrainOutcome {
  attempted: number
  sent: number
  failed: number
  skippedByCap: number
  remainingToday: number
  failures: Array<{ id: string; to: string; error: string }>
  previewed: Array<{ id: string; to: string; subject: string; locale: string }>
}

export async function drainOnce(
  deps: DrainDeps,
  options: DrainOptions = {},
): Promise<DrainOutcome> {
  const batch = options.batch ?? DEFAULT_BATCH
  const dailyCap = options.dailyCap ?? DEFAULT_DAILY_CAP

  const outcome: DrainOutcome = {
    attempted: 0,
    sent: 0,
    failed: 0,
    skippedByCap: 0,
    remainingToday: 0,
    failures: [],
    previewed: [],
  }

  const alreadySent = await deps.sentToday()
  const headroom = Math.max(0, dailyCap - alreadySent)
  outcome.remainingToday = headroom

  if (headroom === 0) {
    // Not an error. The queue is working as designed: delayed, not dropped.
    const waiting = await deps.claim(batch)
    outcome.skippedByCap = waiting.length
    return outcome
  }

  const rows = await deps.claim(Math.min(batch, headroom))
  const appUrl = deps.appUrl()

  for (const row of rows) {
    /*
     * Retired without ever reaching the provider. MAX_ATTEMPTS is passed so
     * markFailed stamps failed_at immediately: there is no future in which a
     * reserved domain becomes routable, so a retry would only repeat the call.
     */
    if (isUndeliverable(row.to_email)) {
      if (!options.dryRun) {
        await deps.markFailed(row.id, MAX_ATTEMPTS, 'Unroutable address: reserved domain (RFC 2606 / mDNS .local). Not attempted.')
        outcome.failed += 1
        outcome.failures.push({ id: row.id, to: row.to_email, error: 'unroutable reserved domain' })
      }
      continue
    }

    const who = await deps.recipient(row.to_user_id)
    const rendered = renderEmail({
      template: row.template,
      subject: row.subject,
      payload: row.payload ?? {},
      locale: who.locale,
      name: who.name,
      appUrl,
    })

    if (options.dryRun) {
      outcome.previewed.push({
        id: row.id,
        to: row.to_email,
        subject: rendered.subject,
        locale: who.locale,
      })
      continue
    }

    outcome.attempted += 1

    const result = await deps.send({
      to: row.to_email,
      subject: rendered.subject,
      html: rendered.html,
      text: rendered.text,
    })

    if (result.ok) {
      await deps.markSent(row.id)
      outcome.sent += 1
    } else {
      const error = result.error ?? 'unknown error'
      /*
       * attempts + 1 is passed rather than incremented in SQL so the give-up
       * boundary is decided in one place and is visible to the test. A row on
       * its fifth failure stops being eligible because the claim query filters
       * attempts < MAX_ATTEMPTS, and markFailed stamps failed_at at exactly
       * that point.
       */
      await deps.markFailed(row.id, row.attempts + 1, error)
      outcome.failed += 1
      outcome.failures.push({ id: row.id, to: row.to_email, error })
    }
  }

  return outcome
}
