'use server'

import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { getAppClaims, can } from '@/lib/auth/claims'
import { createClient } from '@/lib/supabase/server'
import { dbId } from '@/lib/db/id'

/**
 * ═══════════════════════════════════════════════════════════════════════════
 * Marking a recipe or menu item in use, or not.
 *
 * ╔═══════════════════════════════════════════════════════════════════════════╗
 * ║ A STANDING DECISION, NOT A SETTING ON ONE PAPER.                          ║
 * ║                                                                           ║
 * ║ A dish comes off the menu once, and every paper generated afterwards      ║
 * ║ should be free of it — including papers generated by somebody who never   ║
 * ║ saw this screen. So the flag lives on the row rather than in the          ║
 * ║ generator's form state, and generatePaper() reads it whatever the request ║
 * ║ says.                                                                     ║
 * ║                                                                           ║
 * ║ IT CHANGES NO QUESTION. Not the text, not the status, not the topic, and  ║
 * ║ not any paper already generated — those stay true records of what was     ║
 * ║ asked at the time. The only thing that changes is which questions a       ║
 * ║ FUTURE draw considers.                                                    ║
 * ╚═══════════════════════════════════════════════════════════════════════════╝
 * ═══════════════════════════════════════════════════════════════════════════
 */

const usageInput = z.object({
  itemId: dbId(),
  inUse: z.boolean(),
})

export type SetItemUsageResult = { ok: true } | { ok: false; message: string }

const DENIED = 'You are not permitted to change the question bank.'

export async function setItemUsage(raw: unknown): Promise<SetItemUsageResult> {
  const claims = await getAppClaims()

  /*
   * bank.write, the same permission that edits a question — because this
   * decides what an exam may ask about, which is the same kind of authority.
   * Checked here AND enforced by the bank_items_write policy: a Server Action
   * is a public endpoint, and this predicate is not the only thing standing
   * between a stranger and the row.
   */
  if (!can(claims, 'bank.write')) return { ok: false, message: DENIED }

  const parsed = usageInput.safeParse(raw)
  if (!parsed.success) return { ok: false, message: 'That item could not be identified.' }

  const supabase = await createClient()

  const { error, data } = await supabase
    .from('bank_items')
    .update({ in_use: parsed.data.inUse, updated_at: new Date().toISOString() })
    .eq('id', parsed.data.itemId)
    .is('deleted_at', null)
    .select('id')

  if (error) return { ok: false, message: error.message }

  /*
   * RLS returning no rows is not an error from Postgres — it is an update that
   * matched nothing. Reported as a refusal rather than a success, or the
   * screen would show an item as withdrawn while the draw still admits it.
   */
  if (!data || data.length === 0) return { ok: false, message: DENIED }

  // The generate screen counts the pool server-side, so it has to re-render
  // for the new eligible figure to be the one the button is gated on.
  revalidatePath('/papers/generate')

  return { ok: true }
}
