-- ═══════════════════════════════════════════════════════════════════════════
-- 0083 — Retire the email backlog that accumulated while no drain existed.
--
-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║ 1,369 ROWS, NONE EVER SENT, BECAUSE THE DRAIN WAS NEVER WRITTEN.         ║
-- ║                                                                          ║
-- ║ 0007 created email_outbox and described a drain job that sends "within    ║
-- ║ the free-tier daily cap". The queue worked perfectly; nothing ever        ║
-- ║ emptied it. Every enqueue since has simply accumulated.                   ║
-- ║                                                                          ║
-- ║ WHY THESE ARE NOT SENT NOW THAT A DRAIN EXISTS:                          ║
-- ║                                                                          ║
-- ║   · They are stale. exam-assigned notices from weeks ago, for exams       ║
-- ║     already sat or long closed. "Your exam opens soon" arriving three     ║
-- ║     weeks late is worse than silence.                                     ║
-- ║   · They are mostly not real. 92 distinct recipients against 21 real      ║
-- ║     accounts — the bulk were generated by seed and check scripts, and     ║
-- ║     address example.com and bookends-test.local, which cannot receive.    ║
-- ║   · One real person has 75 waiting. Delivering those at once is           ║
-- ║     indistinguishable from spam and risks the sending domain.             ║
-- ║   · 1,369 against a 100/day tier is fourteen days of quota spent on mail  ║
-- ║     nobody needs, while genuinely new notifications queue behind it.      ║
-- ║                                                                          ║
-- ║ So: mark, do not send; and do not delete. failed_at plus last_error keeps ║
-- ║ the record of what was queued and why it never went — the table is a      ║
-- ║ queue, and this is the honest way to close a queue entry.                 ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝
--
-- THE CUTOFF IS A LITERAL, NOT now(). A migration runs once here and again on
-- every other environment at a different wall-clock time; now() would abandon
-- whatever happened to be pending then, including mail queued seconds earlier
-- by a working system. A fixed instant abandons exactly the historical backlog
-- and is idempotent on re-run.
-- ═══════════════════════════════════════════════════════════════════════════

update public.email_outbox
   set failed_at  = now(),
       last_error = 'Abandoned by migration 0083: queued before an email drain existed. '
                    'Not sent because the notice was stale and the backlog would have '
                    'consumed roughly two weeks of the sending quota.'
 where sent_at    is null
   and failed_at  is null
   and created_at <  timestamptz '2026-08-25 00:00:00+00';

comment on table public.email_outbox is
  'Queue, not a send log. Features enqueue here; the drain in src/lib/notifications/drain.ts sends within the free-tier daily cap, priority then age, and is invoked by POST /api/cron/drain-email. Never call the email provider inline — that is how a 300-recipient action blows the quota. Rows are never deleted: sent_at, failed_at, attempts and last_error are the record of what happened.';
